# name: ğŸš€ Deploy website

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'other/*'
#       - '.gitignore'
#       - 'package.json'
#       - 'vite.config.ts'
#       # - "svgo.config.js"
#       - 'src/**'
#       - '.github/workflows/**'

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# jobs:
#   deploy:
#     if: github.event.repository.fork == false
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}

#     runs-on: ubuntu-latest
#     steps:
#       - name: ğŸ“¥ Checkout
#         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

#       - name: ğŸ”§ Setup Bun
#         uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
#         with:
#           bun-version: latest

#       # - name: ğŸ“¦ Cache Bun dependencies
#       #   uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
#       #   with:
#       #     path: |
#       #       ~/.bun/install/cache
#       #     key: bun-cache-${{ hashFiles('**/bun.lock') }}

#       - name: ğŸ“¦ Install Bun dependencies
#         run: bun install

#       - name: ğŸ› ï¸ Build website
#         run: bun run build

#       - name: ğŸ“¤ Upload artifact
#         uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
#         with:
#           path: dist

#       - name: ğŸš€ Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
